ExampleSignalR/Models/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ExampleSignalR.Models
{
    public class LoginViewModel
    {
        public string Usuario { get; set; }
        public string Senha { get; set; }
    }
}

ExampleSignalR/Controllers/AutenticacaoController.cs
using System.Web.Mvc;
using System.Web.Security;
using ExampleSignalR.Models;

namespace ExampleSignalR.Controllers
{
    public class AutenticacaoController : Controller
    {
        [AllowAnonymous]
        public ActionResult Login()
        {
            
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginViewModel viewModel, string returnUrl)
        {
            if (ModelState.IsValid)
            {
                Membership.ValidateUser(viewModel.Usuario, viewModel.Senha);
                FormsAuthentication.SetAuthCookie(viewModel.Usuario, false);

                if (!string.IsNullOrWhiteSpace(returnUrl))
                    return Redirect(returnUrl);

                return RedirectToAction("Index", "Home");
            }

            return View(viewModel);
        }
    }
}

ExampleSignalR/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ExampleSignalR.Autenticacao;
using ExampleSignalR.Contexto.EF;
using ExampleSignalR.Models;

namespace ExampleSignalR.Controllers
{
    public class HomeController : Controller
    {
        [Autorizacao(Roles = new[] { Permissao.Administrador })]
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Autocomplete()
        {
            return View();
        }

        public JsonResult PesquisaServicos(string term)
        {
            using (var contexto = new GenesisEntities())
            {
                var query = (from s in contexto.vwServicoLinear
                             where s.Descricao.Contains(term)

                             select new
                                        {
                                            Id = s.ID,
                                            CodigoInterno = s.CodigoInterno,
                                            Servico = s.Descricao
                                        })
                    .OrderBy(o => o.Servico)
                    .AsNoTracking()
                    .ToList();

                return Json(query, JsonRequestBehavior.AllowGet);
            }
        }

        public ActionResult AdicionarServico(long idServico)
        {
            using (var contexto = new GenesisEntities())
            {
                var servico = contexto.vwServicoClassificado.SingleOrDefault(e => e.ID == idServico);
                var codigoInterno = string.Format("{0}.", servico.Pai);
                
                var query = (from s in contexto.vwServicoClassificado
                             where s.IDTipo == 2 && s.CodigoInterno.StartsWith(codigoInterno)
                             select new
                                        {
                                            Id = s.ID,
                                            CodigoInterno = s.CodigoInterno,
                                            Servico = s.NomeServico
                                        }).ToList();

                return Json(query, JsonRequestBehavior.AllowGet);
            }
        }
    }
}

ExampleSignalR/Controllers/JasmineController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExampleSignalR.Controllers
{
    public class JasmineController : Controller
    {
        //
        // GET: /Jasmine/

        public ActionResult Index()
        {
            return View();
        }

    }
}

ExampleSignalR/Controllers/PropostaComercialController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ExampleSignalR.Controllers
{
    public class PropostaComercialController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

    }
}

ExampleSignalR/Views/Autenticacao/Login.cshtml
@model ExampleSignalR.Models.LoginViewModel

@{
    ViewBag.Title = "Login";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section styles
{
    <style type="text/css">
        .form-signin {
            max-width: 300px;
            padding: 19px 29px 29px;
            margin: 0 auto 20px;
            background-color: #fff;
            border: 1px solid #e5e5e5;
            -webkit-border-radius: 5px;
            -moz-border-radius: 5px;
            border-radius: 5px;
            -webkit-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            -moz-box-shadow: 0 1px 2px rgba(0,0,0,.05);
            box-shadow: 0 1px 2px rgba(0,0,0,.05);
        }

            .form-signin .form-signin-heading,
            .form-signin .checkbox {
                margin-bottom: 10px;
            }

            .form-signin input[type="text"],
            .form-signin input[type="password"] {
                font-size: 16px;
                height: auto;
                margin-bottom: 15px;
                padding: 7px 9px;
            }
    </style>
}

@using (Html.BeginForm())
{
    <div class="form-signin">
        <h2 class="form-signin-heading">Autenticação</h2>
        @Html.TextBoxFor(model => model.Usuario, new { @class = "input-block-level", @placeholder = "Email" })
        @Html.PasswordFor(model => model.Senha, new { @class = "input-block-level", @placeholder = "Senha" })
        <button class="btn btn-large btn-primary" type="submit">Sign in</button>
    </div>
}

ExampleSignalR/Views/Home/Autocomplete.cshtml
@{
    ViewBag.Title = "Autocomplete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="span12">
    <div class="input-append">
        <input class="span8" id="servico" type="text">
        <button class="btn" id="adicionarServico" type="button">+</button>
        <button class="btn" id="limparServicos" type="button">Limpar</button>
    </div>
</div>

<table id="tabelaServicos" class="table table-striped">
    <thead>
        <tr>
            <th class="span2">Código</th>
            <th>Serviço</th>
        </tr>
    </thead>
    <tbody>
    </tbody>
</table>

<script id="testeTmpl" type="text/x-jquery-tmpl">
    <tr>
        <td>${CodigoInterno}</td>
        <td>${Servico}</td>
    </tr>
</script>

@section scripts
{
    <script type="text/javascript">

        function formatarServico(item) {
            if (item.Tipo == 1)
                return "<strong>" + item.CodigoInterno + " - " + item.Servico + "</strong>";

            return item.CodigoInterno + " - " + item.Servico;
        }

        $(function() {

            var cache = { };

            $("#adicionarServico").click(function () {
                $("#servico").val('');
                $.getJSON(window.appUrl + 'Home/AdicionarServico', { idServico: $("#servico").data('id') }, function (response) {
                    $("#testeTmpl").tmpl(response).appendTo("#tabelaServicos");
                });
            });

            $("#limparServicos").click(function() {
                $("#testeTmpl").tmpl(null).appendTo("#tabelaServicos");
                $("#tabelaServicos tbody").empty();
            });

            $("#servico").autocomplete({
                minLength: 4,

                select: function(event, ui) {
                    $("#servico").val(ui.item.CodigoInterno + " - " + ui.item.Servico);
                    $("#servico").data('id', ui.item.Id);
                    return false;
                },

                source: function(request, response) {
                    var term = request.term;
                    if (term in cache) {
                        response(cache[term]);
                        return;
                    }

                    $.getJSON(window.appUrl + 'Home/PesquisaServicos', request, function(data, status, xhr) {
                        cache[term] = data;
                        response(data);
                    });
                }
            }).data("autocomplete")._renderItem = function(ul, item) {
                return $("<li>")
                    .data("item.autocomplete", item)
                    .append("<a>" + formatarServico(item) + "</a>")
                    .appendTo(ul);
            };
        });
    </script>
}

ExampleSignalR/Views/Home/Grafico.cshtml
@{
    ViewBag.Title = "Grafico";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Grafico</h2>

<div id="charts-container" style="min-width: 400px; height: 400px; margin: 0 auto"></div>

@section scripts
{
    @Scripts.Render("~/bundles/highcharts")
    <script type="text/javascript">
        var chart;
        $(function () {

            var dataChart = @(new HtmlString(Json.Encode(ViewBag.Chart)));

            var categorias = $.map(dataChart, function(item) {
                return item.Item1;
            });

            var defaultOptions = {
                chart: {
                    renderTo: 'charts-container',
                    type: 'line',
                    marginRight: 130,
                    marginBottom: 25
                },
                title: {
                    text: 'Gráfico',
                    x: -20 //center
                },
                subtitle: {
                    text: 'Connect Informática',
                    x: -20
                },
                xAxis: {
                    categories: categorias
                },
                yAxis: {
                    title: {
                        text: 'Quantidade'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },
                tooltip: {
                    formatter: function () {
                        return '<b>' + this.series.name + '</b><br/>' +
                            this.x + ': ' + this.y;
                    }
                },
                legend: {
                    layout: 'vertical',
                    align: 'right',
                    verticalAlign: 'top',
                    x: -10,
                    y: 100,
                    borderWidth: 0
                },
                series: []
            };

            chart = new Highcharts.Chart(defaultOptions);
        });
    </script>
}

ExampleSignalR/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div id="chart-container"></div>
<div id="chart-container-2"></div>

@section scripts
{
    @Scripts.Render("~/bundles/highcharts")
    <script type="text/javascript">
        $(function () {

            HighchartsCustom.create({
                title: {
                    text: 'Gráfico - Proposta Comercial'
                },
                
                xAxis: {
                    categories: ['Jan', 'Fev', 'Mar', 'Abr', 'Mai', 'Jun', 'Jul', 'Ago', 'Set', 'Out', 'Nov', 'Dez']
                },
                
                yAxis: {
                    title: {
                        text: 'Quantidade'
                    },
                    plotLines: [{
                        value: 0,
                        width: 1,
                        color: '#808080'
                    }]
                },

                plotOptions: {
                    line: {
                        dataLabels: {
                            enabled: true
                        },
                        enableMouseTracking: false
                    }
                }
            }, 'Home/GraficoProposta');
            
            HighchartsCustom.create({
                chart: {
                    renderTo: 'chart-container-2',
                    type: 'column'
                },
                
                yAxis: [{
                    title: {
                        text: 'Quantidade'
                    },
                    
                    stackLabels: {
                        enabled: true,
                        style:
                        {
                            fontWeight: 'bold',
                            color:
                            (Highcharts.theme && Highcharts.theme.textColor) || 'gray'
                        }
                    }
                }, {
                    title: {
                        text: ''
                    },

                    opposite: true
                }],
                
                title: {
                    text: 'Gráfico - Quantidade de Pessoas cadastradas por Unidade'
                },
                
                plotOptions: {
                    column: {
                        stacking: 'normal',
                        dataLabels: {
                            enabled: false,
                            color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white'
                        }
                    }
                }
            }, 'Home/GraficoUnidadePessoa', function (chart, data) {
                               
                chart.xAxis[0].setCategories(data.categories);
                
                var somaPorUnidade = [], somaTodasUnidades = [];

                $.each(data.categories, function (i) {
                    var t = 0;
                    $.each(data.series, function (item, serieData) {
                        t += serieData[i];
                    });

                    somaPorUnidade.push(t);
                });

                for (var i = 0; i < somaPorUnidade.length; i++) {
                    var t = somaTodasUnidades[somaTodasUnidades.length - 1] || 0;
                    somaTodasUnidades.push(t + somaPorUnidade[i]);
                }

                chart.addSeries({ name: 'TOTAL POR UNIDADE', type: 'spline', data: somaPorUnidade, yAxis: 0 });
                chart.addSeries({ name: 'TOTAL ACUMULADO', type: 'line', data: somaTodasUnidades, yAxis: 0 });

                $.map(data.series, function(data, name) {
                    chart.addSeries({ name: name, data: data, type: 'column', yAxis: 0 });
                });

            });

        });
    </script>
}

ExampleSignalR/Views/Jasmine/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutTests.cshtml";
}

@section scripts
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/jquery.customAutocomplete.js")"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/specs/customAutocompleteTests.js")"></script>
    
    <script type="text/javascript">
        (function () {
            var jasmineEnv = jasmine.getEnv();
            jasmineEnv.updateInterval = 250;

            var htmlReporter = new jasmine.HtmlReporter();
            jasmineEnv.addReporter(htmlReporter);
            
            jasmineEnv.specFilter = function (spec) {
                return htmlReporter.specFilter(spec);
            };

            var currentWindowOnload = window.onload;
            window.onload = function () {
                if (currentWindowOnload) {
                    currentWindowOnload();
                }

                //document.querySelector('.version').innerHTML = jasmineEnv.versionString();
                execJasmine();
            };

            function execJasmine() {
                jasmineEnv.execute();
            }
        })();
    </script>
}

ExampleSignalR/Views/PropostaComercial/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<div class="span2 pull-left">
    <input type="text" class="span1" data-bind="value: numeroProposta" />
</div>
<div class="span10">
    <button class="btn btn-primary" data-bind="click: salvarProposta">Salvar Proposta</button>
</div>

@section scripts
{
    @Scripts.Render("~/bundles/signalr")
    <script type="text/javascript" src="~/signalr/hubs"></script>
    <script type="text/javascript" src="@Url.Content("~/Scripts/monitorar-propostas.js")"></script>
    <script type="text/javascript">
        $(function() {
            var monitor = new window.Monitor.Server();

            $.connection.hub.start();

            ko.applyBindings(monitor);
        });
    </script>
}

ExampleSignalR/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css/themes/bootstrap/css")
    @Styles.Render("~/css/bootstrap")
    @Styles.Render("~/css/autosuggest")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

    <!--[if lt IE 9]>
    <link rel="stylesheet" type="text/css" href="css/custom-theme/jquery.ui.1.9.2.ie.css"/>
    <![endif]-->

    <script type="text/javascript">
        window.appUrl = '@Url.Content("~/")';
    </script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand" href="#">Project name</a>
                <div class="nav-collapse collapse">
                    <ul class="nav">
                        <li class="active"><a href="#">Home</a></li>
                        <li>@Html.ActionLink("Login", "Login", "Autenticacao")</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

    <div class="container">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/json")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/knockout")

    @RenderSection("scripts", required: false)
</body>
</html>

ExampleSignalR/Views/Shared/_LayoutTests.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/css/jasmine")
    @Scripts.Render("~/bundles/modernizr")
    @RenderSection("styles", required: false)

    <script type="text/javascript">
        window.appUrl = '@Url.Content("~/")';
    </script>
</head>
<body>
    @RenderBody()

    @Scripts.Render("~/bundles/json")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jasmine")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/knockout")

    @RenderSection("scripts", required: false)
</body>
</html>